# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  serialized_pb=_b('\n\nchat.proto\"#\n\x05Login\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0e\n\x06passwd\x18\x02 \x02(\t\"$\n\x08LoginMsg\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x0c\n\x04name\x18\x02 \x02(\t\"8\n\x07SendMsg\x12\x0e\n\x06\x46romid\x18\x01 \x02(\x03\x12\x0c\n\x04toId\x18\x02 \x02(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\t\"-\n\nreceiveMsg\x12\x0e\n\x06\x46romid\x18\x01 \x02(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Login.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passwd', full_name='Login.passwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=49,
)


_LOGINMSG = _descriptor.Descriptor(
  name='LoginMsg',
  full_name='LoginMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LoginMsg.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='LoginMsg.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=87,
)


_SENDMSG = _descriptor.Descriptor(
  name='SendMsg',
  full_name='SendMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Fromid', full_name='SendMsg.Fromid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toId', full_name='SendMsg.toId', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='SendMsg.content', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=145,
)


_RECEIVEMSG = _descriptor.Descriptor(
  name='receiveMsg',
  full_name='receiveMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Fromid', full_name='receiveMsg.Fromid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='receiveMsg.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['LoginMsg'] = _LOGINMSG
DESCRIPTOR.message_types_by_name['SendMsg'] = _SENDMSG
DESCRIPTOR.message_types_by_name['receiveMsg'] = _RECEIVEMSG

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Login)
  ))
_sym_db.RegisterMessage(Login)

LoginMsg = _reflection.GeneratedProtocolMessageType('LoginMsg', (_message.Message,), dict(
  DESCRIPTOR = _LOGINMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:LoginMsg)
  ))
_sym_db.RegisterMessage(LoginMsg)

SendMsg = _reflection.GeneratedProtocolMessageType('SendMsg', (_message.Message,), dict(
  DESCRIPTOR = _SENDMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:SendMsg)
  ))
_sym_db.RegisterMessage(SendMsg)

receiveMsg = _reflection.GeneratedProtocolMessageType('receiveMsg', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:receiveMsg)
  ))
_sym_db.RegisterMessage(receiveMsg)


# @@protoc_insertion_point(module_scope)
